### ISSUE TITLE
Can you list the complete list of options allowed?

### ISSUE THREAD

**Issue by rodoabad** [gskachkov/karma-phantomjs2-launcher#4]

**Comment by gskachkov** [comment]
Sorry, not sure that I understand what exact opetions do you need. 
There is only one property that added by this launcher PHANTOMJS2_DOWNLOAD_URL it is described in readme. 
All other options are inherited from karma project, you can check in [karma conf](http://karma-runner.github.io/0.13/config/browsers.html)

**Comment by rodoabad** [comment]
@gskachkov Thanks. I thought there were other ones apart from the Karma conf.
